### ISSUE TITLE
is the paper available?

### ISSUE THREAD

**Issue by lifengcs** [Roudgers/DCFNet#1]
Hi! This is an excellent work, I have read the corresponding code. Is the paper available, I want to read the paper for better understanding. Thanks!

**Comment by Roudgers** [comment]
Thank you for your attention. We are revising the final paper to promote the readability for readers.
&nbsp;The final version will be released after the ICCV 2021 meeting.&nbsp;
Thanks.

---Original---
From: "Feng ***@***.***&gt;
Date: Sat, Aug 7, 2021 18:17 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Roudgers/DCFNet] is the paper available? (#1)




 
Hi! This is an excellent work, I have read the corresponding code. Is the paper available, I want to read the paper for better understanding. Thanks!
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lifengcs** [comment]
> Thank you for your attention. We are revising the final paper to promote the readability for readers. &nbsp;The final version will be released after the ICCV 2021 meeting.&nbsp; Thanks.
> […](#)
> ---Original--- From: "Feng ***@***.***&gt; Date: Sat, Aug 7, 2021 18:17 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [Roudgers/DCFNet] is the paper available? (#1) Hi! This is an excellent work, I have read the corresponding code. Is the paper available, I want to read the paper for better understanding. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I see, thanks for your reply.
