### ISSUE TITLE
您好，请教下您关于Visal数据集问题

### ISSUE THREAD

**Issue by aflyingnoob** [Roudgers/DCFNet#4]
visal数据集在评测的时候， 是只考虑标定的label吗？比如大多数图片数量远大于标定的label数目（visal一般只用来测试）。

**Comment by Roudgers** [comment]
你好，不知道你说的标定是什么意思，我理解应该为标注的帧。是的，通常我们只对比标注了的视频帧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月10日(周日) 晚上10:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Roudgers/DCFNet] 您好，请教下您关于Visal数据集问题 (#4)




 
visal数据集在评测的时候， 是只考虑标定的label吗？比如大多数图片数量远大于标定的label数目（visal一般只用来测试）。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
